djangoSQ/SiQuoia/ranking/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from ranking import views

urlpatterns = patterns('',
	url(r'^$', login_required(views.QRanking.as_view()), name='q_ranking'),
)

djangoSQ/SiQuoia/siquoia/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from siquoia import views

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.sq_top, name="sq_top"),
    url(r'^question/', include('question.urls', namespace="question")),
    url(r'^squser/', include('squser.urls', namespace="squser")),
    url(r'^ranking/', include('ranking.urls', namespace="ranking")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', TemplateView.as_view(template_name="siquoia/sq_login.html"), name="sq_login"),
    url(r'^accounts/auth/$', views.sq_auth, name='sq_auth'),
    url(r'^accounts/logout/$', views.sq_logout, name='sq_logout'),
    url(r'^accounts/register/$', views.sq_register, name='sq_register'),
    url(r'^accounts/register_success$', TemplateView.as_view(template_name='siquoia/sq_register_success.html'), name='sq_register_success'),
)

djangoSQ/SiQuoia/squser/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from squser import views

urlpatterns = patterns('',
	url(r'^$', login_required(views.user_top), name='sq_user_top'),
	url(r'^start$', login_required(views.sq_start), name='sq_start'),

	# Packet Select
	url(r'^pck$', login_required(views.PkC1.as_view()), name='c1_list'),
	url(r'^pck(?P<pk>\d+)/$', login_required(views.PkC2.as_view()), name='c2_list'),
	url(r'^pck(?P<c1_pk>\d+)/(?P<pk>\d+)/$', login_required(views.PkC3.as_view()), name='c3_list'),

	# Packet Confirm
	url(r'^confirmation$', login_required(views.pk_confirm), name='pk_confirm'),
	url(r'^confirmation(?P<c1_pk>\d+)/$', login_required(views.pk_confirm), name='pk_confirm'),
	url(r'^confirmation(?P<c1_pk>\d+)/(?P<c2_pk>\d+)/$', login_required(views.pk_confirm), name='pk_confirm'),
	url(r'^confirmation(?P<c1_pk>\d+)/(?P<c2_pk>\d+)/(?P<c3_pk>\d+)/$', login_required(views.pk_confirm), name='pk_confirm'),

	url(r'^pk_get$', login_required(views.pk_get), name='pk_get'),

	url(r'^quiz$', login_required(views.sq_quiz), name='sq_quiz'),
	url(r'^next$', login_required(views.next), name='next'),

	url(r'^done$', login_required(views.done), name='done'),


	url(r'^buy$', login_required(views.sq_buy_sq), name='sq_buy_sq'),

	url(r'^buysq$', login_required(views.buysq), name='buysq'),

	#url(r'^success$', login_required(views.pk_success), name='pk_success'),
)

djangoSQ/SiQuoia/question/models.py
from django.db import models


# model for the top most category 
class Category1(models.Model):
	# the category name
	name = models.CharField(max_length=50)
	# the "toString" method
	def __unicode__(self):
		return self.name

# model for the 2nd level sub-category
class Category2(models.Model):
	# super category
	category = models.ForeignKey(Category1)
	# the category name
	name = models.CharField(max_length=50)
	# the "toString" method
	def __unicode__(self):
		return self.name

# model for the 3rd level sub-category
class Category3(models.Model):
	# super category
	category = models.ForeignKey(Category2)
	# the category name
	name = models.CharField(max_length=50)
	# the "toString" method
	def __unicode__(self):
		return self.name		

# model for a single question
class Question(models.Model):
	# the question
	text = models.CharField(max_length=500, blank=False)
	# category it belongs to
	category = models.ForeignKey(Category3)
	# number of times answered right by all users
	num_marked_right = models.IntegerField(default=0)
	# number of times answered wrong by all users
	num_marked_wrong = models.IntegerField(default=0)
	# number of times answered by all users
	def num_answered(self):
		return self.num_marked_right + self.num_marked_wrong
	num_answered.integer = True
	# easiness of the question
	def easiness(self):
		return self.num_marked_right - self.num_marked_wrong;
	easiness.integer = True
	# the "toString" method
	def __unicode__(self):
		return self.text

class Choice(models.Model):
	# the choice text
	text = models.CharField(max_length=200, blank=False)
	# question it belongs to
	question = models.ForeignKey(Question)
	# true only if correct choice
	is_correct = models.BooleanField(blank=False, default=False)
	is_correct.short_description = 'Mark correct answer'
	# the "toString" method
	def __unicode__(self):
		return self.text

djangoSQ/SiQuoia/squser/models.py
from django.db import models
from question.models import Question
from django.contrib.auth.models import User

class Packet(models.Model):
	# questions in the packet
	questions = models.ManyToManyField(Question)

class Trial(models.Model):
	question = models.ForeignKey(Question)
	correct = models.BooleanField(default=False)

class Completed(models.Model):
	trial = models.ManyToManyField(Trial)

class SQUserInfo(models.Model):
	# associated user
	user = models.OneToOneField(User)
	# total points
	sq_points = models.IntegerField(default=0)
	# user can have one packet at a time
	packet = models.OneToOneField(Packet)
	trial = models.OneToOneField(Completed)

djangoSQ/SiQuoia/squser/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views import generic

import random

from question.models import Question, Category1, Category2, Category3, Choice
from squser.models import *

def user_top(request):
	return render(request, 'squser/sq_user_top.html');

def sq_start(request):
	return render(request, 'squser/sq_start.html');

def pk_confirm(request, c1_pk=-1, c2_pk=-1, c3_pk=-1):
	user = request.user
	userInfo = SQUserInfo.objects.get(user=user)

	if userInfo.sq_points < 20:
		return render(request, 'squser/sorry.html', {'sq':userInfo.sq_points});

	if c1_pk == -1:
		cName = 'All'
		cType = 'all'
		pk = 0
	elif c2_pk == -1:
		c = Category1.objects.get(pk=c1_pk)
		cName = c.name
		cType = 'c1'
		pk = c.pk
	elif c3_pk == -1:
		c = Category2.objects.get(pk=c2_pk)
		cName = c.name
		cType = 'c2'
		pk = c.pk
	else:
		c = Category3.objects.get(pk=c3_pk)
		cName = c.name
		cType = 'c3'
		pk = c.pk
	

	return render(request, 'squser/pk_confirm.html', {'cName' : cName, 'cType':cType, 'pk':pk ,'sq':userInfo.sq_points});

def pk_get(request):
	cType = request.POST['cType']
	pk = request.POST['pk']
	p = Packet()
	p.save()

	while p.questions.count() < 15:
		p.questions.add(getRandQ(cType, int(pk)))

	p.save()
	t = Completed()
	t.save()

	user = request.user
	userInfo = SQUserInfo.objects.get(user=user)
	userInfo.packet = p
	userInfo.trial = t
	userInfo.save()

	sq = userInfo.sq_points - 20
	userInfo.sq_points = sq
	userInfo.save()

	return render(request, 'squser/pk_success.html');

def getRandQ(cType, pk):
	if cType == 'all':
		return getRandQAll()
	elif cType == 'c1':
		return getRandQC1(pk)
	elif cType == 'c2':
		return getRandQC2(pk)
	else: 
		return getRandQC3(pk)

def getRandQAll():
	c1Set = Category1.objects
	rand_idx = random.randint(0, c1Set.count() - 1)
	rand_c1 = c1Set.all()[rand_idx]
	return getRandQC1(rand_c1.pk)

def getRandQC1(pk):
	c1 = Category1.objects.get(pk=pk)
	c2Set = c1.category2_set
	rand_idx = random.randint(0, c2Set.count() - 1)
	rand_c2 = c2Set.all()[rand_idx]
	return getRandQC2(rand_c2.pk)

def getRandQC2(pk):
	c2 = Category2.objects.get(pk=pk)
	c3Set = c2.category3_set
	rand_idx = random.randint(0, c3Set.count() - 1)
	rand_c3 = c3Set.all()[rand_idx]
	return getRandQC3(rand_c3.pk)

def getRandQC3(pk):
	c3 = Category3.objects.get(pk=pk)
	qSet = c3.question_set
	rand_idx = random.randint(0, qSet.count() - 1)
	return qSet.all()[rand_idx]


def sq_quiz(request):
	user = request.user
	userInfo = SQUserInfo.objects.get(user=user)
	p = userInfo.packet
	
	if p.questions.count() == 0:
		return HttpResponseRedirect('/squser/done')

	q = p.questions.all()[0]
	return render(request, 'squser/sq_quiz.html', {'q':q});


def next(request):

	user = request.user
	userInfo = SQUserInfo.objects.get(user=user)
	p = userInfo.packet
	if p.questions.count() == 0:
		return HttpResponseRedirect('/squser/done')	
	q = p.questions.all()[0]

	correct = False
	try:
		selected_choice = q.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		q.num_marked_wrong += 1
		q.save()
	else:
		if selected_choice.is_correct:
			q.num_marked_right += 1
			q.save()
			correct = True
		else:
			q.num_marked_wrong += 1
			q.save()

	t = Trial(question=q, correct=correct)
	t.save()
	userInfo.trial.trial.add(t)
	p.questions.remove(q)
	p.save()
	userInfo.save()


	return HttpResponseRedirect('/squser/quiz')


def done(request):
	user = request.user
	userInfo = SQUserInfo.objects.get(user=user)
	t = userInfo.trial
	score = 0
	for trial in t.trial.all():
		if trial.correct:
			score = score + 1
	return render(request, 'squser/done.html', {'t':t, 'score':score});


class PkC1(generic.ListView):
	template_name = 'squser/c1_list.html'
	context_object_name = 'c1_list'

	def get_queryset(self):
		return Category1.objects.order_by('name')

class PkC2(generic.DetailView):
	model = Category1
	template_name = 'squser/c2_list.html'
	context_object_name = 'c1'

class PkC3(generic.DetailView):
	model = Category2
	template_name = 'squser/c3_list.html'
	context_object_name = 'c2'


def sq_buy_sq(request):
	user = request.user
	userInfo = SQUserInfo.objects.get(user=user)

	return render(request, 'squser/sq_buy_sq.html', {'sq':userInfo.sq_points});

def buysq(request):
	price = request.POST['total']
	if is_number(price):
		user = request.user
		userInfo = SQUserInfo.objects.get(user=user)
		sq = int(price) + userInfo.sq_points
		userInfo.sq_points = sq
		userInfo.save()
		return render(request, 'squser/thankyou.html');
	else:
		return render(request, 'squser/sq_buy_sq.html', {'error':"Please enter a number without decimal places."});

def is_number(s):
    try:
        int(s)
        return True
    except ValueError:
        return False

djangoSQ/SiQuoia/squser/templates/squser/c1_list.html
{% extends "siquoia/base.html" %}

{% block content %}

<h1>Category</h1>
<h2><a href="{% url 'squser:c1_list' %}">Packet</a></h2>

{% if c1_list %}
<ul>
	<li><a href="{% url 'squser:pk_confirm' %}">All</a></li>
	{% for c1 in c1_list %}
		<li><a href="{% url 'squser:c2_list' c1.id %}">{{ c1.name }}</a></li>
	{% endfor %}
</ul>

{% else %}
	<p>No category</p>
{% endif %}
<a href="{% url 'squser:sq_user_top' %}">Back</a>
{% endblock %}

djangoSQ/SiQuoia/squser/templates/squser/c2_list.html
{% extends "siquoia/base.html" %}

{% block content %}

<h1>{{ c1.name }}</h1>
<h2><a href="{% url 'squser:c1_list' %}">Packet</a></h2>
<h2><a href="{% url 'squser:c2_list' c1.id %}">{{ c1.name }}</a></h2>

<ul>
	<li><a href="{% url 'squser:pk_confirm' c1.id %}">All</a></li>
	{% for c2 in c1.category2_set.all %}
		<li><a href="{% url 'squser:c3_list' c1.id c2.id %}">{{c2.name}}</a></li>
	{% endfor %}
</ul>
<a href="{% url 'squser:c1_list' %}">Back</a>

{% endblock %}

djangoSQ/SiQuoia/squser/templates/squser/c3_list.html
{% extends "siquoia/base.html" %}

{% block content %}

{% with  c1=c2.category %}

<h1>{{ c2.name }}</h1>
<h2><a href="{% url 'squser:c1_list' %}">Packet</a></h2>
<h2><a href="{% url 'squser:c2_list' c1.id %}">{{ c1.name }}</a></h2>
<h2><a href="{% url 'squser:c3_list' c1.id c2.id %}">{{ c2.name }}</a></h2>

<ul>
	<li><a href="{% url 'squser:pk_confirm' c1.id c2.id %}">All</a></li>
	{% for c3 in c2.category3_set.all %}
		<li><a href="{% url 'squser:pk_confirm' c1.id c2.id c3.id %}">{{c3.name}}</a></li>
	{% endfor %}
</ul>
<a href="{% url 'squser:c2_list' c1.id %}">Back</a>
{% endwith %}

{% endblock %}

djangoSQ/SiQuoia/squser/templates/squser/done.html
{% extends "siquoia/base.html" %}

{% block content %}

<h1>Done!</h1>

<ul>
<li><a href="{% url 'squser:c1_list' %}">Buy New Packet</a></li>
</ul>

<table>
	<tr>
		<th>Question</th>
		<th>Marked Correct</th>


	</tr>
	{% for trial in t.trial.all %}
	<tr>
		<td>{{ trial.question.text }}</td>
		<td>{{ trial.correct }}</td>
	</tr>

	{% endfor %}
	<tr>
		<td> Total Score</td>
		<td> {{score}}</td>
	</tr>
</table>

{% endblock %}

djangoSQ/SiQuoia/squser/templates/squser/pk_confirm.html
{% extends "siquoia/base.html" %}

{% block content %}

<h1>Confirmantion</h1>

<ul>
	<li>Category: {{cName}}</li>
	<li>Prices: 20 SQ</li>
	<li>You have: {{sq}} SQ</li>
</ul>

<form method="POST" action="{% url 'squser:pk_get' %}">
{% csrf_token %}
  <input type='hidden' name='cType' value='{{cType}}' />
  <input type='hidden' name='pk' value='{{pk}}' />
  <input type="submit" value="Get Packet!" />
</form>

{% endblock %}

djangoSQ/SiQuoia/squser/templates/squser/pk_success.html
{% extends "siquoia/base.html" %}

{% block content %}

<h1>Success!</h1>

<ul>
<li><a href="{% url 'squser:sq_user_top' %}">Home</a></li>
</ul>

{% endblock %}

djangoSQ/SiQuoia/squser/templates/squser/sorry.html
{% extends "siquoia/base.html" %}

{% block content %}

<h1>You dont have enough SQ...</h1>

<ul>
	<li>Prices: 20 SQ</li>
	<li>You have: {{sq}} SQ</li>
	<li><a href="{% url 'squser:sq_buy_sq' %}">Get SQ!</a></li>
</ul>


{% endblock %}

djangoSQ/SiQuoia/squser/templates/squser/sq_buy_sq.html
{% extends "siquoia/base.html" %}

{% block content %}

<h1>Register</h1>

{% if error %}<p><strong>{{error}}</p></strong>{% endif %}

<form method="POST" action={% url 'squser:buysq' %}>
	{% csrf_token %}
	<label for="total">Purchasing SQ:</label>
	<input id="total" name="total" type="number" />
	<br />

	<label for="name">Name On Card:</label>
	<input id="name" name="name" type="text" />
	<br />

	<label for="address">Street Address:</label>
	<input id="address" name="address" type="text" />
	<br />

	<label for="address">Card Number:</label>
	<input id="number" name="number" type="number" />
	<br />
<br />
<input type="submit" value="Buy SQ!" />
</form>

<ul><li>Total SQ as of now: {{sq}}</li></ul>

{% endblock %}

djangoSQ/SiQuoia/squser/templates/squser/sq_quiz.html
{% extends "siquoia/base.html" %}

{% block content %}


<h1>{{ q.text }}</h1>

<form action="{% url 'squser:next' %}" method="post">
{% csrf_token %}
{% for choice in q.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}">{{ choice.text }}</label><br />
{% endfor %}
<input type="submit" value="Next" />
</form>



{% endblock %}

djangoSQ/SiQuoia/squser/templates/squser/sq_register.html
<!doctype html>
<html>
<head>
  <title>SiQuoia</title>
  <meta charset="utf-8">
  <!-- <link rel="stylesheet" type="text/css" href="path/to/stylesheet" /> -->
</head>
<body>

<h1>SiQuoia Register</h1>

{% if error_message %}<p><strong>{{error_message}}</p></strong>{% endif %}

<form method="POST" action="{% url 'squser:sq_register_submit' %}">
{% csrf_token %}
  <label for="username_field">Username:</label>
  <input type="text" name="username" id="username_field" /><br />
  <label for="password_field">Password:</label> 
  <input type="password" name="password" id="password_field" /><br />
  <label for="password_field_cnf">Password (confirm):</label> 
  <input type="password" name="password_cnf" id="password_field_cnf" /><br />

  <input type="submit" value="Register" />
</form>

</body>
</html>

djangoSQ/SiQuoia/squser/templates/squser/sq_start.html
{% extends "siquoia/base.html" %}

{% block content %}

<h1>Start Quiz</h1>

<ul>
	<li><a href="{% url 'squser:sq_quiz' %}">Start!</a></li>
</ul>

{% endblock %}

djangoSQ/SiQuoia/squser/templates/squser/sq_user_top.html
{% extends "siquoia/base.html" %}

{% block content %}

<h1>User Top</h1>

<ul>
	<li><a href="{% url 'squser:sq_start' %}">Play Quiz</a></li>
	<li><a href="{% url 'squser:sq_buy_sq' %}">Buy SiQuoias</a></li>
	<li><a href="{% url 'squser:c1_list' %}">Get Packet</a></li>
	<li><a href="{% url 'ranking:q_ranking' %}">Ranking</a></li>
	<li><a href="{% url 'sq_logout' %}">Logout</a></li>
</ul>


{% endblock %}

djangoSQ/SiQuoia/squser/templates/squser/thankyou.html
{% extends "siquoia/base.html" %}

{% block content %}

<h1>Thank You!</h1>

<ul>
<li><a href="{% url 'squser:sq_user_top' %}">Home</a></li>
</ul>

{% endblock %}