djangoSQ/SiQuoia/question/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from question import views

urlpatterns = patterns('',
	url(r'^$', login_required(views.C1View.as_view()), name='c1_list'),
	url(r'^(?P<pk>\d+)/$', login_required(views.C2View.as_view()), name='c2_list'),
	url(r'^(?P<c1_pk>\d+)/(?P<pk>\d+)/$', login_required(views.C3View.as_view()), name='c3_list'),
	url(r'^(?P<c1_pk>\d+)/(?P<c2_pk>\d+)/(?P<pk>\d+)/$', login_required(views.QuestionListView.as_view()), name='question_list'),
	url(r'^(?P<c1_pk>\d+)/(?P<c2_pk>\d+)/(?P<c3_pk>\d+)/(?P<pk>\d+)/$', login_required(views.AnswerQuestionView.as_view()), name='answer_question'),
	url(r'(?P<c1_pk>\d+)/(?P<c2_pk>\d+)/(?P<c3_pk>\d+)/(?P<q_id>\d+)/submit$', login_required(views.submit), name='submit'),
)

djangoSQ/SiQuoia/siquoia/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from siquoia import views

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.sq_top, name="sq_top"),
    url(r'^question/', include('question.urls', namespace="question")),
    url(r'^squser/', include('squser.urls', namespace="squser")),
    url(r'^ranking/', include('ranking.urls', namespace="ranking")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', TemplateView.as_view(template_name="siquoia/sq_login.html"), name="sq_login"),
    url(r'^accounts/auth/$', views.sq_auth, name='sq_auth'),
    url(r'^accounts/logout/$', views.sq_logout, name='sq_logout'),
    url(r'^accounts/register/$', views.sq_register, name='sq_register'),
    url(r'^accounts/register_success$', TemplateView.as_view(template_name='siquoia/sq_register_success.html'), name='sq_register_success'),
)

djangoSQ/SiQuoia/squser/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from squser import views

urlpatterns = patterns('',
	url(r'^$', login_required(views.user_top), name='sq_user_top'),
	url(r'^start$', login_required(views.sq_start), name='sq_start'),

	# Packet Select
	url(r'^pck$', login_required(views.PkC1.as_view()), name='c1_list'),
	url(r'^pck(?P<pk>\d+)/$', login_required(views.PkC2.as_view()), name='c2_list'),
	url(r'^pck(?P<c1_pk>\d+)/(?P<pk>\d+)/$', login_required(views.PkC3.as_view()), name='c3_list'),

	# Packet Confirm
	url(r'^confirmation$', login_required(views.pk_confirm), name='pk_confirm'),
	url(r'^confirmation(?P<c1_pk>\d+)/$', login_required(views.pk_confirm), name='pk_confirm'),
	url(r'^confirmation(?P<c1_pk>\d+)/(?P<c2_pk>\d+)/$', login_required(views.pk_confirm), name='pk_confirm'),
	url(r'^confirmation(?P<c1_pk>\d+)/(?P<c2_pk>\d+)/(?P<c3_pk>\d+)/$', login_required(views.pk_confirm), name='pk_confirm'),

	url(r'^pk_get$', login_required(views.pk_get), name='pk_get'),

	url(r'^quiz$', login_required(views.sq_quiz), name='sq_quiz'),
	url(r'^next$', login_required(views.next), name='next'),

	url(r'^done$', login_required(views.done), name='done'),


	url(r'^buy$', login_required(views.sq_buy_sq), name='sq_buy_sq'),

	url(r'^buysq$', login_required(views.buysq), name='buysq'),

	#url(r'^success$', login_required(views.pk_success), name='pk_success'),
)

djangoSQ/SiQuoia/question/models.py
from django.db import models


# model for the top most category 
class Category1(models.Model):
	# the category name
	name = models.CharField(max_length=50)
	# the "toString" method
	def __unicode__(self):
		return self.name

# model for the 2nd level sub-category
class Category2(models.Model):
	# super category
	category = models.ForeignKey(Category1)
	# the category name
	name = models.CharField(max_length=50)
	# the "toString" method
	def __unicode__(self):
		return self.name

# model for the 3rd level sub-category
class Category3(models.Model):
	# super category
	category = models.ForeignKey(Category2)
	# the category name
	name = models.CharField(max_length=50)
	# the "toString" method
	def __unicode__(self):
		return self.name		

# model for a single question
class Question(models.Model):
	# the question
	text = models.CharField(max_length=500, blank=False)
	# category it belongs to
	category = models.ForeignKey(Category3)
	# number of times answered right by all users
	num_marked_right = models.IntegerField(default=0)
	# number of times answered wrong by all users
	num_marked_wrong = models.IntegerField(default=0)
	# number of times answered by all users
	def num_answered(self):
		return self.num_marked_right + self.num_marked_wrong
	num_answered.integer = True
	# easiness of the question
	def easiness(self):
		return self.num_marked_right - self.num_marked_wrong;
	easiness.integer = True
	# the "toString" method
	def __unicode__(self):
		return self.text

class Choice(models.Model):
	# the choice text
	text = models.CharField(max_length=200, blank=False)
	# question it belongs to
	question = models.ForeignKey(Question)
	# true only if correct choice
	is_correct = models.BooleanField(blank=False, default=False)
	is_correct.short_description = 'Mark correct answer'
	# the "toString" method
	def __unicode__(self):
		return self.text

djangoSQ/SiQuoia/question/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic


from question.models import Question, Category1, Category2, Category3, Choice

# shows the top level category
class C1View(generic.ListView):
	template_name = 'question/c1_list.html'
	context_object_name = 'c1_list'

	def get_queryset(self):
		return Category1.objects.order_by('name')

# shows the 2nd level category contained in the given 1st level category
class C2View(generic.DetailView):
	model = Category1
	template_name = 'question/c2_list.html'
	context_object_name = 'c1'

# shows the 3rd level category contained in the given 2nd level category
class C3View(generic.DetailView):
	model = Category2
	template_name = 'question/c3_list.html'
	context_object_name = 'c2'

class QuestionListView(generic.DetailView):
	model = Category3
	template_name = 'question/question_list.html'
	context_object_name = 'c3'

class AnswerQuestionView(generic.DetailView):
	model = Question
	template_name = 'question/answer_question.html'
	context_object_name = 'q'

def submit(request, c1_pk, c2_pk, c3_pk, q_id):
	q = get_object_or_404(Question, pk=q_id)
	try:
		selected_choice = q.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		q.num_marked_wrong += 1
		q.save()
		return HttpResponse('Wrong!')
	else:
		if selected_choice.is_correct:
			q.num_marked_right += 1
			q.save()
			return HttpResponse('Correct!')
		else:
			q.num_marked_wrong += 1
			q.save()
			return HttpResponse('Wrong!')

djangoSQ/SiQuoia/question/templates/question/answer_question.html
{% extends "siquoia/base.html" %}

{% block content %}

{% with c3=q.category %}
{% with c2=c3.category %}
{% with c1=c2.category %}

{# <a href="{% url 'question:c2_list' c1.id %}">Back</a> #}
<h1>{{ q.text }}</h1>
<h2><a href="{% url 'question:c2_list' c1.id %}">{{ c1.name }}</a></h2>
<h2><a href="{% url 'question:c3_list' c1.id c2.id %}">{{ c2.name }}</a></h2>
<h2><a href="{% url 'question:question_list' c1.id c2.id c3.id %}">{{ c3.name }}</a></h2>
<h2><a href=".">{{ q.text }}</a></h2>

<form action="{% url 'question:submit' c1.id c2.id c3.id q.id %}" method="post">
{% csrf_token %}
{% for choice in q.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}">{{ choice.text }}</label><br />
{% endfor %}
<input type="submit" value="Next" />
</form>
{% endwith %}
{% endwith %}
{% endwith %}

{% endblock %}

djangoSQ/SiQuoia/question/templates/question/c1_list.html
{% extends "siquoia/base.html" %}

{% block content %}

<h1>Category</h1>

{% if c1_list %}
<ul>
	<li>All</li>
	{% for c1 in c1_list %}
		<li><a href="{% url 'question:c2_list' c1.id %}">{{ c1.name }}</a></li>
	{% endfor %}
</ul>

{% else %}
	<p>No category</p>
{% endif %}

{% endblock %}

djangoSQ/SiQuoia/question/templates/question/c2_list.html
{% extends "siquoia/base.html" %}

{% block content %}

<h1>{{ c1.name }}</h1>
<h2><a href="{% url 'question:c2_list' c1.id %}">{{ c1.name }}</a></h2>

<ul>
	<li>All</li>
	{% for c2 in c1.category2_set.all %}
		<li><a href="{% url 'question:c3_list' c1.id c2.id %}">{{c2.name}}</a></li>
	{% endfor %}
</ul>
<a href="{% url 'question:c1_list' %}">Back</a>

{% endblock %}

djangoSQ/SiQuoia/question/templates/question/c3_list.html
{% extends "siquoia/base.html" %}

{% block content %}

{% with  c1=c2.category %}

<h1>{{ c2.name }}</h1>
<h2><a href="{% url 'question:c2_list' c1.id %}">{{ c1.name }}</a></h2>
<h2><a href="{% url 'question:c3_list' c1.id c2.id %}">{{ c2.name }}</a></h2>

<ul>
	<li>All</li>
	{% for c3 in c2.category3_set.all %}
		<li><a href="{% url 'question:question_list' c1.id c2.id c3.id %}">{{c3.name}}</a></li>
	{% endfor %}
</ul>
<a href="{% url 'question:c2_list' c1.id %}">Back</a>
{% endwith %}

{% endblock %}

djangoSQ/SiQuoia/question/templates/question/question_list.html
{% extends "siquoia/base.html" %}

{% block content %}

{% with c2=c3.category %}
{% with c1=c2.category %}

<h1>{{ c3.name }}</h1>
<h2><a href="{% url 'question:c2_list' c1.id %}">{{ c1.name }}</a></h2>
<h2><a href="{% url 'question:c3_list' c1.id c2.id %}">{{ c2.name }}</a></h2>
<h2><a href="{% url 'question:question_list' c1.id c2.id c3.id %}">{{ c3.name }}</a></h2>

<ul>
	{% for question in c3.question_set.all %}
		<li><a href="{% url 'question:answer_question' c1.id c2.id c3.id question.id %}">{{ question.text }}</li>
	{% endfor %}
</ul>

<a href="{% url 'question:c3_list' c1.id c2.id %}">Back</a>

{% endwith %}
{% endwith %}

{% endblock %}